version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    parallelism: 1

    steps:
      - checkout

      - run: 
          name: test
          command: go test -v

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

